server:
  port: ${nan.server.port}

spring:
  profiles:
    active: dev

  main:
    allow-circular-references: true

  datasource:
    druid:
      driver-class-name: ${nan.datasource.driver-class-name}
      url: jdbc:mysql://${nan.datasource.host}:${nan.datasource.port}/${nan.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${nan.datasource.username}
      password: ${nan.datasource.password}

  redis:
    host: ${nan.redis.host}
    port: ${nan.redis.port}
    password: ${nan.redis.password}
    database: ${nan.redis.database}


mybatis:
  #Dao 配置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.WM.entity
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      nan:
        mapper: debug
        service: info
        controller: info

jwt:
  #JWT令牌密钥
  admin-secret-key: ${nan.admin.secret-key}
  #过期时间
  admin-ttl: ${nan.admin.ttl}
  #JWT请求头名字
  admin-token-name: ${nan.admin.token-name}
  #JWT令牌密钥
  user-secret-key: ${nan.user.secret-key}
  #过期时间
  user-ttl: ${nan.user.ttl}
  #JWT请求头名字
  user-token-name: ${nan.user.token-name}


alioss:
  endpoint: ${nan.alioss.endpoint}
  access-key-id: ${nan.alioss.access-key-id}
  access-key-secret: ${nan.alioss.access-key-secret}
  bucket-name: ${nan.alioss.bucket-name}

wechat:
  appid: ${nan.wechat.appid}
  secret: ${nan.wechat.secret}
