server:
  port: ${nan.server.port}

spring:
  profiles:
    active: dev

  main:
    allow-circular-references: true

  datasource:
    druid:
      driver-class-name: ${nan.datasource.driver-class-name}
      url: jdbc:mysql://${nan.datasource.host}:${nan.datasource.port}/${nan.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${nan.datasource.username}
      password: ${nan.datasource.password}

  redis:
    host: ${nan.redis.host}
    port: ${nan.redis.port}
    password: ${nan.redis.password}
    database: ${nan.redis.database}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.WM.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      nan:
        mapper: debug
        service: info
        controller: info

jwt:
  admin-secret-key: ${nan.admin.secret-key}
  admin-ttl: ${nan.admin.ttl}
  admin-token-name: ${nan.admin.token-name}

  user-secret-key: ${nan.user.secret-key}
  user-ttl: ${nan.user.ttl}
  user-token-name: ${nan.user.token-name}


alioss:
  endpoint: ${nan.alioss.endpoint}
  access-key-id: ${nan.alioss.access-key-id}
  access-key-secret: ${nan.alioss.access-key-secret}
  bucket-name: ${nan.alioss.bucket-name}

wechat:
  appid: ${nan.wechat.appid}
  secret: ${nan.wechat.secret}
  mchid: ${nan.wechat.mchid}
  mchSerialNo: ${nan.wechat.mchSerialNo}
  privateKeyFilePath: ${nan.wechat.privateKeyFilePath}
  apiV3Key: ${nan.wechat.apiV3Key}
  weChatPayCertFilePath: ${nan.wechat.weChatPayCertFilePath}
  notifyUrl: ${nan.wechat.notifyUrl}
  refundNotifyUrl: ${nan.wechat.refundNotifyUrl}
